-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2025-04-13 09:45:31.59

-- tables
-- Table: TOURIST_BUREAU_BUSES
CREATE TABLE IF NOT EXISTS TOURIST_BUREAU_BUSES (
    id integer NOT NULL CONSTRAINT TOURIST_BUREAU_BUSES_pk PRIMARY KEY AUTOINCREMENT,
    number text NOT NULL,
    model text NOT NULL,
    totalMileage real NOT NULL,
    CONSTRAINT TOURIST_BUREAU_BUSES_ak_1 UNIQUE (number)
);

-- Table: TOURIST_BUREAU_CREW_MEMBERS
CREATE TABLE IF NOT EXISTS TOURIST_BUREAU_CREW_MEMBERS (
    id integer NOT NULL CONSTRAINT TOURIST_BUREAU_CREW_MEMBERS_pk PRIMARY KEY AUTOINCREMENT,
    lastName text NOT NULL,
    employeeNumber text NOT NULL,
    experience integer NOT NULL,
    category text NOT NULL,
    address text NOT NULL,
    birthYear integer NOT NULL,
    busId integer NOT NULL,
    CONSTRAINT TOURIST_BUREAU_CREW_MEMBERS_ak_1 UNIQUE (employeeNumber),
    CONSTRAINT TOURIST_BUREAU_CREW_MEMBERS_TOURIST_BUREAU_BUSES FOREIGN KEY (busId)
    REFERENCES TOURIST_BUREAU_BUSES (id)
);

-- Table: TOURIST_BUREAU_CREW_PAYMENTS
CREATE TABLE IF NOT EXISTS TOURIST_BUREAU_CREW_PAYMENTS (
    id integer NOT NULL CONSTRAINT TOURIST_BUREAU_CREW_PAYMENTS_pk PRIMARY KEY AUTOINCREMENT,
    busId integer NOT NULL,
    amount real NOT NULL,
    paymentDate date NOT NULL,
    periodStart date NOT NULL,
    periodEnd date NOT NULL,
    CONSTRAINT TOURIST_BUREAU_BUSES_TOURIST_BUREAU_CREW_PAYMENTS FOREIGN KEY (busId)
    REFERENCES TOURIST_BUREAU_BUSES (id)
);

-- Table: TOURIST_BUREAU_ROUTES
CREATE TABLE IF NOT EXISTS TOURIST_BUREAU_ROUTES (
    id integer NOT NULL CONSTRAINT TOURIST_BUREAU_ROUTES_pk PRIMARY KEY AUTOINCREMENT,
    name text NOT NULL,
    startPoint text NOT NULL,
    endPoint text NOT NULL,
    distance real NOT NULL,
    CONSTRAINT TOURIST_BUREAU_ROUTES_ak_1 UNIQUE (name)
);

-- Table: TOURIST_BUREAU_TRIPS
CREATE TABLE IF NOT EXISTS TOURIST_BUREAU_TRIPS (
    id integer NOT NULL CONSTRAINT TOURIST_BUREAU_TRIPS_pk PRIMARY KEY AUTOINCREMENT,
    busId integer NOT NULL,
    departureDate date NOT NULL,
    arrivalDate date NOT NULL,
    routeName text NOT NULL,
    passengersCount integer NOT NULL,
    ticketPrice real NOT NULL,
    CONSTRAINT TOURIST_BUREAU_TRIPS_TOURIST_BUREAU_BUSES FOREIGN KEY (busId)
    REFERENCES TOURIST_BUREAU_BUSES (id),
    CONSTRAINT TOURIST_BUREAU_TRIPS_TOURIST_BUREAU_ROUTES FOREIGN KEY (routeName)
    REFERENCES TOURIST_BUREAU_ROUTES (name)
);

-- Table: TOURIST_BUREAU_USERS
CREATE TABLE IF NOT EXISTS TOURIST_BUREAU_USERS (
    id integer NOT NULL CONSTRAINT TOURIST_BUREAU_USERS_pk PRIMARY KEY AUTOINCREMENT,
    username text NOT NULL,
    password text NOT NULL,
    role text NOT NULL,
    crewMemberId integer,
    CONSTRAINT TOURIST_BUREAU_USERS_ak_1 UNIQUE (username),
    CONSTRAINT TOURIST_BUREAU_USERS_TOURIST_BUREAU_CREW_MEMBERS FOREIGN KEY (crewMemberId)
    REFERENCES TOURIST_BUREAU_CREW_MEMBERS (id)
);

-- End of file.

